### ISSUE TITLE
:humanize

### ISSUE THREAD

**Issue by jeremyruppel** [jeremyruppel/walrus#10]
Wonder if this would actually be useful to anyone.

http://as.rubyonrails.org/

**Comment by kagd** [comment]
Did you want to implement this? I am kind of in agreement with you, how many people would actually use it?

It wouldn't be that difficult to add. Capitalize the first word and remove `_id` if present.

**Comment by jeremyruppel** [comment]
Yeah I'm with you here, it would be easy but let's not add it until someone has a need for it. I'm going to close this for now, and we can reopen if necessary.
